import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "GestPro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/gestpro.png" />
      </head>
      <body className={`antialiased h-dvh`}>
        {children}
      </body>
    </html>
  );
}
